/**
 * @copyright
 * Copyright 2025 JeongHan-Bae &lt;mastropseudo\@gmail.com&gt;
 * <br>
 * Licensed under the MIT License.
 */
/**
 * @file lunisolar.h
 * @brief Header-only lunisolar calendar mapping library.
 *
 * @details
 *
 * This library maps Gregorian dates to the Chinese lunisolar calendar and back
 * by decoding generated <code>lunisolar_data</code> tables.
 * <br>
 * The data tables are generated by scripts that extract authoritative calendar
 * data from <code>sxtwl</code>. The resulting library is a minimal and portable
 * C++20-only header with no external runtime dependencies.
 * <br>
 * The implementation follows the Chinese Mainland definition of the Chinese
 * lunisolar calendar. No locale abstraction is provided.
 * <br>
 * <div>
 * Except for numeric output, every enum-to-string mapping is a strict one-to-one
 * mapping based on Chinese Mainland conventions and derived orthographies.
 * </div>
 * <ul>
 * <li>Mainland simplified Chinese as one Hanzi writing form.</li>
 * <li>Mainland traditional Chinese as the other Hanzi writing form.</li>
 * <li>Hanyu Pinyin as one pronunciation-based spelling form.</li>
 * <li>Chinese-standard Joseonjok EonMun (Hangul) as the other pronunciation-based spelling form.</li>
 * </ul>
 * <br>
 * These mappings are aligned with the same Hanzi basis and the corresponding
 * pronunciation and orthographic standards used in Mainland China.
 * <br>
 * No locale is provided for any non-Mainland language, regional variant, or
 * dialect. The library does not provide any non-Hanzi language labels beyond
 * the supported romanization and EonMun forms.
 * <br>
 * In practice, the textual surface is limited to two Hanzi writing styles and
 * two pronunciation-based systems.
 * <br>
 * Mainland non-Hanzi dialect writing systems and ethnic minority languages are
 * also unsupported, because they do not satisfy this library's requirement of
 * phonetic annotation for the same Hanzi basis rather than translation of
 * Chinese into a different language system. Projects that require other
 * mappings should provide their own translation layer.
 *
 * @note
 * Gregorian conversion assumes the proleptic Gregorian calendar and does not
 * model the historical pre-Gregorian transition. In particular, this library
 * does not represent the calendar reform gap introduced in October 1582. The
 * storage model requires every supported Gregorian year to behave as an ordinary
 * Gregorian year with roughly 365 days so that packed annual data stays simple
 * and compact.
 */

#pragma once

#include <array>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <cstddef>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>

/**
 * @brief Lunisolar calendar types, packed-data helpers, and conversion APIs.
 *
 * @details
 * <div>
 * The packed storage model used by this namespace is intentionally simple and
 * space-efficient. Each supported Chinese year is encoded in one
 * <code>std::uint64_t</code> value.
 * </div>
 * <div>
 * Bits 0 to 12 store physical month lengths where 0 means 29 days and 1 means
 * 30 days. Bits 13 to 16 store the leap month number, or 0 when there is no
 * leap month. Bits 17 to 25 store the zero-based Gregorian day-of-year of
 * Chinese New Year. Bits 26 to 34 store the total Chinese year length as a
 * validation field.
 * </div>
 * <div>
 * Solar terms are packed separately. Each Gregorian year stores 24 signed
 * offsets from stable Gregorian base dates. Every term uses 4 bits with the
 * encoding <code>offset + 8</code>, so one year occupies two
 * <code>std::uint64_t</code> words.
 * </div>
 */
namespace lunisolar {

    /**
     * @brief Returns the number of supported years in a closed year range.
     */
    template<int FirstSupportedYear, int LastSupportedYear>
    requires (LastSupportedYear >= FirstSupportedYear)
    [[nodiscard]] consteval std::size_t supported_year_count() {
        return static_cast<std::size_t>(
                static_cast<std::int64_t>(LastSupportedYear)
                - static_cast<std::int64_t>(FirstSupportedYear)
                + std::int64_t{1}
        );
    }

    /**
     * @brief Number of solar terms in one Gregorian year.
     */
    inline constexpr std::size_t solar_term_count = 24;

    /**
     * @brief Number of packed words used to store one Gregorian year's solar terms.
     */
    inline constexpr std::size_t packed_solar_term_word_count = 2;

    /**
     * @brief Error codes returned by checked conversion and lookup APIs.
     */
    enum class error {
        none,
        year_out_of_range,
        invalid_gregorian_date,
        invalid_chinese_month,
        invalid_chinese_day,
        invalid_leap_month
    };

    /**
     * @brief Result wrapper for checked APIs.
     *
     * @tparam T Value type stored on success.
     */
    template<class T>
    struct result {
        /** @brief Converted or computed value. */
        T value{};
        /** @brief Error code for the operation. */
        error ec{error::none};

        /**
         * @brief Returns <code>true</code> when the operation succeeded.
         */
        [[nodiscard]] constexpr explicit operator bool() const noexcept {
            return ec == error::none;
        }
    };

    /**
     * @brief Chinese lunisolar calendar date.
     */
    struct chinese_date {
        /** @brief Chinese calendar year. */
        int year{};
        /** @brief Logical lunar month in the range 1 to 12. */
        unsigned month{};
        /** @brief Day within the logical lunar month. */
        unsigned day{};
        /** @brief Whether the date is in the leap instance of the month. */
        bool leap{};

        /**
         * @brief Compares two Chinese dates for equality.
         */
        friend constexpr bool operator==(const chinese_date &, const chinese_date &) = default;
    };

    /**
     * @brief Gregorian calendar date.
     */
    struct gregorian_date {
        /** @brief Gregorian year. */
        int year{};
        /** @brief Gregorian month in the range 1 to 12. */
        unsigned month{};
        /** @brief Gregorian day in the range 1 to 31. */
        unsigned day{};

        /**
         * @brief Compares two Gregorian dates for equality.
         */
        friend constexpr bool operator==(const gregorian_date &, const gregorian_date &) = default;
    };

    /**
     * @brief Local civil time split into calendar and clock fields.
     */
    struct local_date_time_parts {
        /** @brief Local Gregorian date. */
        gregorian_date date{};
        /** @brief Local hour in the range 0 to 23. */
        unsigned hour{};
        /** @brief Local minute in the range 0 to 59. */
        unsigned minute{};
        /** @brief Local second in the range 0 to 59. */
        unsigned second{};

        /**
         * @brief Compares two local date-time values for equality.
         */
        friend constexpr bool operator==(
                const local_date_time_parts &,
                const local_date_time_parts &
        ) = default;
    };

    /**
     * @brief Ten Heavenly Stems.
     */
    enum class heavenly_stem : std::uint8_t {
        jia, yi, bing, ding, wu, ji, geng, xin, ren, gui
    };

    /**
     * @brief Twelve Earthly Branches.
     */
    enum class earthly_branch : std::uint8_t {
        zi, chou, yin, mao, chen, si, wu, wei, shen, you, xu, hai
    };

    /**
     * @brief One sexagenary cycle value.
     */
    struct ganzhi {
        /** @brief Zero-based sexagenary index where 0 is Jia-Zi and 59 is Gui-Hai. */
        std::uint8_t index{};

        /**
         * @brief Constructs the first sexagenary value.
         */
        constexpr ganzhi() noexcept = default;

        /**
         * @brief Constructs a sexagenary value from any unsigned index.
         */
        constexpr explicit ganzhi(unsigned value) noexcept
                : index(static_cast<std::uint8_t>(value % 60U)) {}

        /**
         * @brief Returns the Heavenly Stem component.
         */
        [[nodiscard]] constexpr heavenly_stem stem() const noexcept {
            return static_cast<heavenly_stem>(index % 10U);
        }

        /**
         * @brief Returns the Earthly Branch component.
         */
        [[nodiscard]] constexpr earthly_branch branch() const noexcept {
            return static_cast<earthly_branch>(index % 12U);
        }

        /**
         * @brief Compares two sexagenary values for equality.
         */
        friend constexpr bool operator==(ganzhi, ganzhi) = default;
    };

    /**
     * @brief Four Pillars expressed as sexagenary values.
     */
    struct four_pillars {
        /** @brief Year pillar. */
        ganzhi year{};
        /** @brief Month pillar. */
        ganzhi month{};
        /** @brief Day pillar. */
        ganzhi day{};
        /** @brief Hour pillar. */
        ganzhi hour{};

        /**
         * @brief Compares two Four Pillars values for equality.
         */
        friend constexpr bool operator==(four_pillars, four_pillars) = default;
    };

    /**
     * @brief Stringified Four Pillars value.
     */
    struct four_pillars_text {
        /** @brief Year pillar text. */
        std::string year;
        /** @brief Month pillar text. */
        std::string month;
        /** @brief Day pillar text. */
        std::string day;
        /** @brief Hour pillar text. */
        std::string hour;
    };

    /**
     * @brief Solar-term-based Ganzhi year and month pair.
     */
    struct solar_term_year_month {
        /** @brief Ganzhi year determined by the Li-Chun boundary. */
        int year{};
        /** @brief Ganzhi month where 1 is Yin month and 12 is Chou month. */
        unsigned month{};

        /**
         * @brief Compares two solar-term year-month values for equality.
         */
        friend constexpr bool operator==(
                solar_term_year_month,
                solar_term_year_month
        ) = default;
    };

    /**
     * @brief Output styles for names and labels.
     */
    enum class text_style {
        hans_cn,
        hant_cn,
        pinyin,
        eon_mun_ko_cn,
        numeric
    };

    /**
     * @brief Day-boundary policy for hour-based calculations.
     */
    enum class day_boundary {
        midnight,
        zi_hour
    };

    /**
     * @brief Month source used for Four Pillars month calculation.
     */
    enum class month_basis {
        lunar_month,
        solar_term_month
    };

    /**
     * @brief Twenty-four solar terms in chronological order.
     */
    enum class solar_term : std::uint8_t {
        lichun = 0,
        yushui,
        jingzhe,
        chunfen,
        qingming,
        guyu,

        lixia,
        xiaoman,
        mangzhong,
        xiazhi,
        xiaoshu,
        dashu,

        liqiu,
        chushu,
        bailu,
        qiufen,
        hanlu,
        shuangjiang,

        lidong,
        xiaoxue,
        daxue,
        dongzhi,
        xiaohan,
        dahan
    };

    /**
     * @brief Internal implementation details.
     */
    namespace detail {

        /**
         * @brief Computes a non-negative modulo result.
         */
        [[nodiscard]] constexpr int floor_mod(std::int64_t value, int modulus) noexcept {
            const auto r = static_cast<int>(value % modulus);
            return r < 0 ? r + modulus : r;
        }

        /**
         * @brief Checks whether a Gregorian date is valid.
         */
        [[nodiscard]] constexpr bool valid_gregorian(gregorian_date value) noexcept {
            using namespace std::chrono;
            return year_month_day{
                    year{value.year},
                    month{value.month},
                    day{value.day}
            }.ok();
        }

        /**
         * @brief Converts a Gregorian date to <code>std::chrono::sys_days</code>.
         */
        [[nodiscard]] constexpr std::chrono::sys_days to_sys_days(gregorian_date value) noexcept {
            using namespace std::chrono;
            return sys_days{
                    year{value.year} / month{value.month} / day{value.day}
            };
        }

        /**
         * @brief Converts <code>std::chrono::sys_days</code> to a Gregorian date.
         */
        [[nodiscard]] constexpr gregorian_date from_sys_days(std::chrono::sys_days value) noexcept {
            const std::chrono::year_month_day ymd{value};
            return {
                    static_cast<int>(ymd.year()),
                    static_cast<unsigned>(ymd.month()),
                    static_cast<unsigned>(ymd.day())
            };
        }

        /**
         * @brief Returns the zero-based day-of-year for a Gregorian date.
         */
        [[nodiscard]] constexpr unsigned day_of_year_zero_based(gregorian_date value) noexcept {
            using namespace std::chrono;
            const sys_days current = to_sys_days(value);
            const sys_days first = sys_days{year{value.year} / January / 1};
            return static_cast<unsigned>((current - first).count());
        }

        /**
         * @brief Returns the packed-table index for a supported year.
         */
        [[nodiscard]] constexpr std::size_t year_index(
                int year,
                int first_supported_year
        ) noexcept {
            return static_cast<std::size_t>(year - first_supported_year);
        }

        /**
         * @brief Packed Chinese year layout.
         *
         * @details
         * <div>Bits 0 to 12 store physical month lengths where 0 means 29 days and 1 means 30 days.</div>
         * <div>Bits 13 to 16 store the leap month number, or 0 when no leap month exists.</div>
         * <div>Bits 17 to 25 store the zero-based Gregorian day-of-year of Chinese New Year.</div>
         * <div>Bits 26 to 34 store the full Chinese year length for validation.</div>
         */
        [[nodiscard]] constexpr std::uint16_t packed_month_bits(std::uint64_t value) noexcept {
            return static_cast<std::uint16_t>(value & 0x1FFFULL);
        }

        /**
         * @brief Extracts the leap month field from packed year data.
         */
        [[nodiscard]] constexpr std::uint8_t packed_leap_month(std::uint64_t value) noexcept {
            return static_cast<std::uint8_t>((value >> 13U) & 0xFULL);
        }

        /**
         * @brief Extracts the Chinese New Year day-of-year field from packed year data.
         */
        [[nodiscard]] constexpr std::uint16_t packed_new_year_day(std::uint64_t value) noexcept {
            return static_cast<std::uint16_t>((value >> 17U) & 0x1FFULL);
        }

        /**
         * @brief Extracts the encoded Chinese year length from packed year data.
         */
        [[nodiscard]] constexpr std::uint16_t packed_year_length(std::uint64_t value) noexcept {
            return static_cast<std::uint16_t>((value >> 26U) & 0x1FFULL);
        }

        /**
         * @brief Bias applied to packed solar-term offsets.
         */
        inline constexpr int solar_term_offset_bias = 8;
        /**
         * @brief Bit width of one packed solar-term offset.
         */
        inline constexpr unsigned solar_term_offset_bits = 4;
        /**
         * @brief Bit mask for one packed solar-term offset.
         */
        inline constexpr unsigned solar_term_offset_mask = 0xFU;

        /**
         * @brief Gregorian base month for each solar term.
         */
        inline constexpr std::array<unsigned, solar_term_count> solar_term_base_month{
                2, 2, 3, 3, 4, 4,
                5, 5, 6, 6, 7, 7,
                8, 8, 9, 9, 10, 10,
                11, 11, 12, 12, 1, 1
        };

        /**
         * @brief Gregorian base day for each solar term.
         */
        inline constexpr std::array<unsigned, solar_term_count> solar_term_base_day{
                4, 19, 6, 21, 5, 20,
                6, 21, 6, 21, 7, 23,
                8, 23, 8, 23, 8, 23,
                7, 22, 7, 22, 6, 20
        };

        /**
         * @brief Solar terms that begin Ganzhi months.
         */
        inline constexpr std::array<solar_term, 11> solar_term_month_starts{
                solar_term::lichun,
                solar_term::jingzhe,
                solar_term::qingming,
                solar_term::lixia,
                solar_term::mangzhong,
                solar_term::xiaoshu,
                solar_term::liqiu,
                solar_term::bailu,
                solar_term::hanlu,
                solar_term::lidong,
                solar_term::daxue
        };

        /**
         * @brief Decodes one packed solar-term offset.
         *
         * @details
         * <div>Each Gregorian year stores 24 signed offsets from stable base dates.</div>
         * <div>The packed representation uses 4 bits per term with the encoding <code>offset + 8</code>.</div>
         */
        [[nodiscard]] constexpr int unpack_solar_term_offset(
                const std::array<std::uint64_t, packed_solar_term_word_count> &packed,
                unsigned term_index
        ) noexcept {
            const unsigned bit = term_index * solar_term_offset_bits;
            const unsigned word = bit / 64U;
            const unsigned shift = bit % 64U;

            const auto raw =
                    static_cast<unsigned>((packed[word] >> shift) & solar_term_offset_mask);

            return static_cast<int>(raw) - solar_term_offset_bias;
        }

        /** @brief Simplified Chinese Heavenly Stem names. */
        inline constexpr std::array<std::string_view, 10> stems_hans{
                "甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"
        };

        /** @brief Simplified Chinese Earthly Branch names. */
        inline constexpr std::array<std::string_view, 12> branches_hans{
                "子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"
        };

        /** @brief Chinese-standard Joseonjok EonMun (Hangul) Heavenly Stem names. */
        inline constexpr std::array<std::string_view, 10> stems_eon_mun{
                "갑", "을", "병", "정", "무", "기", "경", "신", "임", "계"
        };

        /** @brief Chinese-standard Joseonjok EonMun (Hangul) Earthly Branch names. */
        inline constexpr std::array<std::string_view, 12> branches_eon_mun{
                "자", "축", "인", "묘", "진", "사", "오", "미", "신", "유", "술", "해"
        };

        /** @brief Hanyu Pinyin Heavenly Stem names. */
        inline constexpr std::array<std::string_view, 10> stems_pinyin{
                "jia", "yi", "bing", "ding", "wu", "ji", "geng", "xin", "ren", "gui"
        };

        /** @brief Hanyu Pinyin Earthly Branch names. */
        inline constexpr std::array<std::string_view, 12> branches_pinyin{
                "zi", "chou", "yin", "mao", "chen", "si", "wu", "wei", "shen", "you", "xu", "hai"
        };

        /** @brief Simplified Chinese solar-term names. */
        inline constexpr std::array<std::string_view, solar_term_count> solar_terms_hans{
                "立春", "雨水", "惊蛰", "春分", "清明", "谷雨",
                "立夏", "小满", "芒种", "夏至", "小暑", "大暑",
                "立秋", "处暑", "白露", "秋分", "寒露", "霜降",
                "立冬", "小雪", "大雪", "冬至", "小寒", "大寒"
        };

        /** @brief Traditional Chinese solar-term names used by this library. */
        inline constexpr std::array<std::string_view, solar_term_count> solar_terms_hant_cn{
                "立春", "雨水", "驚蟄", "春分", "清明", "穀雨",
                "立夏", "小滿", "芒種", "夏至", "小暑", "大暑",
                "立秋", "處暑", "白露", "秋分", "寒露", "霜降",
                "立冬", "小雪", "大雪", "冬至", "小寒", "大寒"
        };

        /** @brief Hanyu Pinyin solar-term names. */
        inline constexpr std::array<std::string_view, solar_term_count> solar_terms_pinyin{
                "lichun", "yushui", "jingzhe", "chunfen", "qingming", "guyu",
                "lixia", "xiaoman", "mangzhong", "xiazhi", "xiaoshu", "dashu",
                "liqiu", "chushu", "bailu", "qiufen", "hanlu", "shuangjiang",
                "lidong", "xiaoxue", "daxue", "dongzhi", "xiaohan", "dahan"
        };

        /**
         * @brief Chinese-standard Joseonjok EonMun (Hangul) solar-term names.
         *
         * @details
         * <div>No Korean initial-sound law is applied in this mapping.</div>
         */
        inline constexpr std::array<std::string_view, solar_term_count> solar_terms_eon_mun{
                "립춘", "우수", "경칩", "춘분", "청명", "곡우",
                "립하", "소만", "망종", "하지", "소서", "대서",
                "립추", "처서", "백로", "추분", "한로", "상강",
                "립동", "소설", "대설", "동지", "소한", "대한"
        };

    }

    /**
     * @brief Converts UTC time to local civil time with a fixed offset.
     */
    template<class Duration>
    [[nodiscard]] constexpr auto local_time(
            std::chrono::sys_time<Duration> utc,
            std::chrono::seconds utc_offset
    ) noexcept {
        using common_duration =
                std::common_type_t<Duration, std::chrono::seconds>;
        return std::chrono::local_time<common_duration>{
                std::chrono::duration_cast<common_duration>(
                        utc.time_since_epoch()
                ) +
                std::chrono::duration_cast<common_duration>(utc_offset)
        };
    }

    /**
     * @brief Extracts the local Gregorian date from a local time point.
     */
    template<class Duration>
    [[nodiscard]] constexpr gregorian_date local_date(
            std::chrono::local_time<Duration> value
    ) noexcept {
        const auto day_point =
                std::chrono::floor<std::chrono::days>(value);
        const std::chrono::year_month_day ymd{
                std::chrono::local_days{day_point.time_since_epoch()}
        };
        return {
                static_cast<int>(ymd.year()),
                static_cast<unsigned>(ymd.month()),
                static_cast<unsigned>(ymd.day())
        };
    }

    /**
     * @brief Extracts the hour field from a local time point.
     */
    template<class Duration>
    [[nodiscard]] constexpr unsigned local_hour(
            std::chrono::local_time<Duration> value
    ) noexcept {
        const auto day_point =
                std::chrono::floor<std::chrono::days>(value);
        const auto elapsed = value - day_point;
        return static_cast<unsigned>(
                std::chrono::duration_cast<std::chrono::hours>(elapsed).count()
        );
    }

    /**
     * @brief Splits a local time point into date and clock fields.
     */
    template<class Duration>
    [[nodiscard]] constexpr local_date_time_parts local_parts(
            std::chrono::local_time<Duration> value
    ) noexcept {
        const auto day_point =
                std::chrono::floor<std::chrono::days>(value);

        const std::chrono::year_month_day ymd{
                std::chrono::local_days{day_point.time_since_epoch()}
        };

        const auto elapsed = value - day_point;
        const auto h = std::chrono::duration_cast<std::chrono::hours>(elapsed);
        const auto m = std::chrono::duration_cast<std::chrono::minutes>(elapsed - h);
        const auto s = std::chrono::duration_cast<std::chrono::seconds>(elapsed - h - m);

        return {
                gregorian_date{
                        static_cast<int>(ymd.year()),
                        static_cast<unsigned>(ymd.month()),
                        static_cast<unsigned>(ymd.day())
                },
                static_cast<unsigned>(h.count()),
                static_cast<unsigned>(m.count()),
                static_cast<unsigned>(s.count())
        };
    }

    /**
     * @brief Converts UTC to local date and clock fields with a fixed offset.
     */
    template<class Duration>
    [[nodiscard]] constexpr local_date_time_parts local_parts(
            std::chrono::sys_time<Duration> utc,
            std::chrono::seconds utc_offset
    ) noexcept {
        return local_parts(local_time(utc, utc_offset));
    }

    template<
            int FirstSupportedYear,
            int LastSupportedYear,
            gregorian_date DayGanzhiAnchorDate,
            unsigned DayGanzhiAnchorIndex,
            const std::array<
                    std::uint64_t,
                    supported_year_count<FirstSupportedYear, LastSupportedYear>()
            > &PackedYears,
            const std::array<
                    std::array<std::uint64_t, packed_solar_term_word_count>,
                    supported_year_count<FirstSupportedYear, LastSupportedYear>()
            > &PackedSolarTerms
    >
    /**
     * @brief Calendar adapter backed by generated packed lunisolar data.
     *
     * @details
     * <div>
     * This class provides constexpr conversion, lookup, and Four Pillars helpers
     * for one generated lunisolar dataset.
     * </div>
     * <div>
     * The packed data is interpreted according to Chinese Mainland calendar rules.
     * Month names, Ganzhi names, and solar-term names are all mapped with fixed
     * one-to-one Chinese-standard tables provided by this header.
     * </div>
     */
    class basic_calendar {
    public:
        /** @brief First supported Chinese and Gregorian year in the packed dataset. */
        static constexpr int first_supported_year = FirstSupportedYear;
        /** @brief Last supported Chinese and Gregorian year in the packed dataset. */
        static constexpr int last_supported_year = LastSupportedYear;

        /** @brief Gregorian anchor date used for day Ganzhi indexing. */
        static constexpr gregorian_date day_ganzhi_anchor_date = DayGanzhiAnchorDate;
        /** @brief Ganzhi index assigned to the anchor date. */
        static constexpr unsigned day_ganzhi_anchor_index = DayGanzhiAnchorIndex % 60U;

        /**
         * @brief Returns the number of supported years in the dataset.
         */
        [[nodiscard]] static constexpr std::size_t supported_year_count() noexcept {
            return lunisolar::supported_year_count<FirstSupportedYear, LastSupportedYear>();
        }

        /** @brief Convenience alias for day durations. */
        using days = std::chrono::days;
        /** @brief Convenience alias for UTC day points. */
        using sys_days = std::chrono::sys_days;

        /**
         * @brief Returns whether a Chinese year is supported.
         */
        [[nodiscard]] static constexpr bool supports_chinese_year(int year) noexcept {
            return year >= first_supported_year && year <= last_supported_year;
        }

        /**
         * @brief Returns whether a Gregorian year is supported.
         */
        [[nodiscard]] static constexpr bool supports_gregorian_year(int year) noexcept {
            return year >= first_supported_year && year <= last_supported_year;
        }

        /**
         * @brief Returns the first Gregorian date representable by the dataset.
         */
        [[nodiscard]] static constexpr gregorian_date first_gregorian_date() noexcept {
            return detail::from_sys_days(
                    std::chrono::sys_days{
                            std::chrono::year{first_supported_year} /
                            std::chrono::January / 1
                    } + days{new_year_day(first_supported_year)}
            );
        }

        /**
         * @brief Returns the last Gregorian date representable by the dataset.
         */
        [[nodiscard]] static constexpr gregorian_date last_gregorian_date() noexcept {
            const int y = last_supported_year;
            const auto start = chinese_new_year(y);
            return detail::from_sys_days(start + days{year_length(y) - 1});
        }

        /**
         * @brief Returns the packed year record for a supported Chinese year.
         */
        [[nodiscard]] static constexpr std::uint64_t packed_year(int year) noexcept {
            if (!supports_chinese_year(year)) {
                return 0;
            }
            return PackedYears[detail::year_index(year, first_supported_year)];
        }

        /**
         * @brief Returns the physical month-length bit field for a Chinese year.
         */
        [[nodiscard]] static constexpr unsigned month_bits(int year) noexcept {
            if (!supports_chinese_year(year)) {
                return 0;
            }
            return detail::packed_month_bits(packed_year(year));
        }

        /**
         * @brief Returns the leap month number for a Chinese year, or 0 when absent.
         */
        [[nodiscard]] static constexpr unsigned leap_month(int year) noexcept {
            if (!supports_chinese_year(year)) {
                return 0;
            }
            return detail::packed_leap_month(packed_year(year));
        }

        /**
         * @brief Returns the zero-based Gregorian day-of-year of Chinese New Year.
         */
        [[nodiscard]] static constexpr unsigned new_year_day(int year) noexcept {
            if (!supports_chinese_year(year)) {
                return 0;
            }
            return detail::packed_new_year_day(packed_year(year));
        }

        /**
         * @brief Returns the total number of days in a Chinese year.
         */
        [[nodiscard]] static constexpr unsigned year_length(int year) noexcept {
            if (!supports_chinese_year(year)) {
                return 0;
            }
            return detail::packed_year_length(packed_year(year));
        }

        /**
         * @brief Returns the number of physical months in a Chinese year.
         */
        [[nodiscard]] static constexpr unsigned physical_month_count(int year) noexcept {
            return leap_month(year) == 0 ? 12U : 13U;
        }

        /**
         * @brief Returns the length of a physical month in days.
         */
        [[nodiscard]] static constexpr unsigned physical_month_days(
                int year,
                unsigned physical_index
        ) noexcept {
            if (!supports_chinese_year(year) ||
                physical_index >= physical_month_count(year)) {
                return 0;
            }

            const auto bits = month_bits(year);
            return ((bits >> physical_index) & 1U) != 0U ? 30U : 29U;
        }

        /**
         * @brief Returns the length of a logical lunar month in days.
         */
        [[nodiscard]] static constexpr unsigned regular_month_days(
                int year,
                unsigned month,
                bool is_leap = false
        ) noexcept {
            const auto physical = physical_month_index(year, month, is_leap);
            if (!physical) {
                return 0;
            }
            return physical_month_days(year, *physical);
        }

        /**
         * @brief Returns the Gregorian day point of Chinese New Year.
         */
        [[nodiscard]] static constexpr sys_days chinese_new_year(int year) noexcept {
            using namespace std::chrono;
            if (!supports_chinese_year(year)) {
                return sys_days{};
            }
            return sys_days{std::chrono::year{year} / January / 1} +
                   days{new_year_day(year)};
        }

        /**
         * @brief Validates a Chinese date against the packed dataset.
         */
        [[nodiscard]] static constexpr bool valid(chinese_date value) noexcept {
            if (!supports_chinese_year(value.year) ||
                value.month < 1 || value.month > 12) {
                return false;
            }

            if (value.leap && leap_month(value.year) != value.month) {
                return false;
            }

            const unsigned count =
                    regular_month_days(value.year, value.month, value.leap);
            return count != 0 && value.day >= 1 && value.day <= count;
        }

        /**
         * @brief Converts a Chinese lunisolar date to a Gregorian date.
         */
        [[nodiscard]] static constexpr result<gregorian_date>
        to_gregorian(chinese_date value) noexcept {
            if (!supports_chinese_year(value.year)) {
                return {{}, error::year_out_of_range};
            }
            if (value.month < 1 || value.month > 12) {
                return {{}, error::invalid_chinese_month};
            }
            if (value.leap && leap_month(value.year) != value.month) {
                return {{}, error::invalid_leap_month};
            }

            const auto physical =
                    physical_month_index(value.year, value.month, value.leap);
            if (!physical) {
                return {{}, error::invalid_chinese_month};
            }

            const unsigned count = physical_month_days(value.year, *physical);
            if (value.day < 1 || value.day > count) {
                return {{}, error::invalid_chinese_day};
            }

            unsigned offset = value.day - 1U;
            for (unsigned i = 0; i < *physical; ++i) {
                offset += physical_month_days(value.year, i);
            }

            return {
                    detail::from_sys_days(chinese_new_year(value.year) + days{offset}),
                    error::none
            };
        }

        /**
         * @brief Converts a Gregorian date to a Chinese lunisolar date.
         */
        [[nodiscard]] static constexpr result<chinese_date>
        from_gregorian(gregorian_date value) noexcept {
            if (!detail::valid_gregorian(value)) {
                return {{}, error::invalid_gregorian_date};
            }

            const sys_days date = detail::to_sys_days(value);
            const sys_days first = chinese_new_year(first_supported_year);
            const sys_days final =
                    chinese_new_year(last_supported_year) +
                    days{year_length(last_supported_year)};

            if (date < first || date >= final) {
                return {{}, error::year_out_of_range};
            }

            int chinese_year = value.year;

            if (chinese_year > last_supported_year) {
                chinese_year = last_supported_year;
            } else {
                if (detail::day_of_year_zero_based(value) < new_year_day(chinese_year)) {
                    --chinese_year;
                }
            }

            if (!supports_chinese_year(chinese_year)) {
                return {{}, error::year_out_of_range};
            }

            unsigned remaining = static_cast<unsigned>(
                    (date - chinese_new_year(chinese_year)).count()
            );

            unsigned physical = 0;
            for (; physical < physical_month_count(chinese_year); ++physical) {
                const unsigned count =
                        physical_month_days(chinese_year, physical);
                if (remaining < count) {
                    break;
                }
                remaining -= count;
            }

            const auto logical =
                    logical_month_from_physical(chinese_year, physical);

            return {
                    chinese_date{
                            chinese_year,
                            logical.month,
                            remaining + 1U,
                            logical.leap
                    },
                    error::none
            };
        }

        /**
         * @brief Returns the year Ganzhi for a Chinese year number.
         */
        [[nodiscard]] static constexpr ganzhi year_ganzhi(int chinese_year) noexcept {
            return ganzhi{
                    static_cast<unsigned>(
                            detail::floor_mod(
                                    static_cast<std::int64_t>(chinese_year) - 1984,
                                    60
                            )
                    )
            };
        }

        /**
         * @brief Returns the month Ganzhi for a Ganzhi year and Ganzhi month number.
         */
        [[nodiscard]] static constexpr ganzhi month_ganzhi(
                int ganzhi_year,
                unsigned month
        ) noexcept {
            if (month < 1 || month > 12) {
                return ganzhi{};
            }

            const auto year_stem =
                    static_cast<unsigned>(year_ganzhi(ganzhi_year).stem());

            const unsigned first_month_stem =
                    ((year_stem % 5U) * 2U + 2U) % 10U;

            const unsigned month_stem =
                    (first_month_stem + month - 1U) % 10U;

            const unsigned month_branch =
                    (month + 1U) % 12U;

            for (unsigned i = 0; i < 60U; ++i) {
                if (i % 10U == month_stem && i % 12U == month_branch) {
                    return ganzhi{i};
                }
            }

            return ganzhi{};
        }

        /**
         * @brief Returns the day Ganzhi for a Gregorian date.
         */
        [[nodiscard]] static constexpr ganzhi day_ganzhi(gregorian_date date) noexcept {
            const auto delta = (
                    detail::to_sys_days(date) -
                    detail::to_sys_days(day_ganzhi_anchor_date)
            ).count();

            return ganzhi{
                    static_cast<unsigned>(
                            detail::floor_mod(
                                    static_cast<std::int64_t>(delta) +
                                    static_cast<std::int64_t>(day_ganzhi_anchor_index),
                                    60
                            )
                    )
            };
        }

        /**
         * @brief Returns the hour Ganzhi for a local Gregorian date and hour.
         */
        [[nodiscard]] static constexpr ganzhi hour_ganzhi(
                gregorian_date date,
                unsigned hour,
                day_boundary boundary = day_boundary::midnight
        ) noexcept {
            if (hour > 23) {
                return ganzhi{};
            }

            auto effective_date = date;
            if (boundary == day_boundary::zi_hour && hour == 23) {
                effective_date = detail::from_sys_days(
                        detail::to_sys_days(date) + days{1}
                );
            }

            const ganzhi day = day_ganzhi(effective_date);
            const auto day_stem =
                    static_cast<unsigned>(day.stem());
            const unsigned hour_branch = ((hour + 1U) / 2U) % 12U;
            const unsigned hour_stem =
                    (2U * (day_stem % 5U) + hour_branch) % 10U;

            for (unsigned i = 0; i < 60U; ++i) {
                if (i % 10U == hour_stem && i % 12U == hour_branch) {
                    return ganzhi{i};
                }
            }
            return ganzhi{};
        }

        /**
         * @brief Returns the hour Ganzhi for a UTC time point with fixed offset conversion.
         */
        template<class Duration>
        [[nodiscard]] static constexpr ganzhi hour_ganzhi(
                std::chrono::sys_time<Duration> utc,
                std::chrono::seconds utc_offset,
                day_boundary boundary = day_boundary::midnight
        ) noexcept {
            const auto local = lunisolar::local_time(utc, utc_offset);
            return hour_ganzhi(
                    lunisolar::local_date(local),
                    lunisolar::local_hour(local),
                    boundary
            );
        }

        /**
         * @brief Returns the hour Ganzhi after validating the derived local date.
         */
        template<class Duration>
        [[nodiscard]] static constexpr result<ganzhi> checked_hour_ganzhi(
                std::chrono::sys_time<Duration> utc,
                std::chrono::seconds utc_offset,
                day_boundary boundary = day_boundary::midnight
        ) noexcept {
            const auto local = lunisolar::local_time(utc, utc_offset);
            const auto date = lunisolar::local_date(local);

            if (!detail::valid_gregorian(date)) {
                return {{}, error::invalid_gregorian_date};
            }

            const auto converted = from_gregorian(date);
            if (!converted) {
                return {{}, converted.ec};
            }

            return {
                    hour_ganzhi(date, lunisolar::local_hour(local), boundary),
                    error::none
            };
        }

        /**
         * @brief Returns the Gregorian date of a solar term.
         */
        [[nodiscard]] static constexpr result<gregorian_date> solar_term_date(
                int gregorian_year,
                solar_term term
        ) noexcept {
            if (!supports_gregorian_year(gregorian_year)) {
                return {{}, error::year_out_of_range};
            }

            const auto index = static_cast<unsigned>(term);
            if (index >= solar_term_count) {
                return {{}, error::invalid_gregorian_date};
            }

            const auto y = detail::year_index(gregorian_year, first_supported_year);
            const int offset =
                    detail::unpack_solar_term_offset(PackedSolarTerms[y], index);

            const auto base =
                    std::chrono::sys_days{
                            std::chrono::year{gregorian_year} /
                            std::chrono::month{detail::solar_term_base_month[index]} /
                            std::chrono::day{detail::solar_term_base_day[index]}
                    };

            return {
                    detail::from_sys_days(base + days{offset}),
                    error::none
            };
        }

        /**
         * @brief Returns the solar-term-based Ganzhi year and month of a date.
         */
        [[nodiscard]] static constexpr result<solar_term_year_month>
        solar_term_year_month_of(gregorian_date date) noexcept {
            if (!detail::valid_gregorian(date)) {
                return {{}, error::invalid_gregorian_date};
            }

            if (!supports_gregorian_year(date.year)) {
                return {{}, error::year_out_of_range};
            }

            const auto current = detail::to_sys_days(date);

            const auto lichun_result = solar_term_date(date.year, solar_term::lichun);
            if (!lichun_result) {
                return {{}, lichun_result.ec};
            }

            const auto lichun = detail::to_sys_days(lichun_result.value);

            int gz_year = date.year;
            if (current < lichun) {
                gz_year -= 1;
            }

            if (!supports_chinese_year(gz_year)) {
                return {{}, error::year_out_of_range};
            }

            if (current < lichun) {
                return {
                        solar_term_year_month{gz_year, 12U},
                        error::none
                };
            }

            unsigned month = 1;

            for (std::size_t i = 1; i < detail::solar_term_month_starts.size(); ++i) {
                const auto term_date = solar_term_date(
                        date.year,
                        detail::solar_term_month_starts[i]
                );
                if (!term_date) {
                    return {{}, term_date.ec};
                }

                if (current >= detail::to_sys_days(term_date.value)) {
                    month = static_cast<unsigned>(i + 1U);
                } else {
                    break;
                }
            }

            return {
                    solar_term_year_month{gz_year, month},
                    error::none
            };
        }

        /**
         * @brief Returns the month Ganzhi using solar-term month boundaries.
         */
        [[nodiscard]] static constexpr result<ganzhi>
        solar_term_month_ganzhi(gregorian_date date) noexcept {
            const auto ym = solar_term_year_month_of(date);
            if (!ym) {
                return {{}, ym.ec};
            }

            return {
                    month_ganzhi(ym.value.year, ym.value.month),
                    error::none
            };
        }

        /**
         * @brief Computes the simplified Four Pillars for a local date and hour.
         *
         * @details
         * <div>
         * The year and month pillars are chosen either from lunar-month boundaries
         * or from solar-term month boundaries, depending on <code>basis</code>.
         * </div>
         */
        [[nodiscard]] static constexpr result<four_pillars> simplified_four_pillars(
                gregorian_date date,
                unsigned hour,
                day_boundary boundary = day_boundary::midnight,
                month_basis basis = month_basis::solar_term_month
        ) noexcept {
            if (hour > 23) {
                return {{}, error::invalid_gregorian_date};
            }

            auto effective_date = date;
            if (boundary == day_boundary::zi_hour && hour == 23) {
                effective_date = detail::from_sys_days(
                        detail::to_sys_days(date) + days{1}
                );
            }

            if (basis == month_basis::lunar_month) {
                const auto chinese = from_gregorian(effective_date);
                if (!chinese) {
                    return {{}, chinese.ec};
                }

                return {
                        four_pillars{
                                year_ganzhi(chinese.value.year),
                                month_ganzhi(chinese.value.year, chinese.value.month),
                                day_ganzhi(effective_date),
                                hour_ganzhi(date, hour, boundary)
                        },
                        error::none
                };
            }

            const auto ym = solar_term_year_month_of(effective_date);
            if (!ym) {
                return {{}, ym.ec};
            }

            return {
                    four_pillars{
                            year_ganzhi(ym.value.year),
                            month_ganzhi(ym.value.year, ym.value.month),
                            day_ganzhi(effective_date),
                            hour_ganzhi(date, hour, boundary)
                    },
                    error::none
            };
        }

        /**
         * @brief Computes the simplified Four Pillars for a UTC time point with fixed offset conversion.
         */
        template<class Duration>
        [[nodiscard]] static constexpr result<four_pillars> simplified_four_pillars(
                std::chrono::sys_time<Duration> utc,
                std::chrono::seconds utc_offset,
                day_boundary boundary = day_boundary::midnight,
                month_basis basis = month_basis::solar_term_month
        ) noexcept {
            const auto local = lunisolar::local_time(utc, utc_offset);

            return simplified_four_pillars(
                    lunisolar::local_date(local),
                    lunisolar::local_hour(local),
                    boundary,
                    basis
            );
        }

    private:
        /**
         * @brief Internal logical month descriptor.
         */
        struct logical_month {
            unsigned month{};
            bool leap{};
        };

        /**
         * @brief Maps a logical month to a physical month index.
         */
        [[nodiscard]] static constexpr std::optional<unsigned>
        physical_month_index(
                int year,
                unsigned month,
                bool is_leap
        ) noexcept {
            if (!supports_chinese_year(year) || month < 1 || month > 12) {
                return std::nullopt;
            }

            const unsigned leap = leap_month(year);
            if (is_leap && leap != month) {
                return std::nullopt;
            }

            if (leap == 0 || month <= leap) {
                if (is_leap) {
                    return month;
                }
                return month - 1U;
            }

            return month;
        }

        /**
         * @brief Maps a physical month index back to its logical month descriptor.
         */
        [[nodiscard]] static constexpr logical_month
        logical_month_from_physical(
                int year,
                unsigned physical
        ) noexcept {
            const unsigned leap = leap_month(year);

            if (leap == 0 || physical < leap) {
                return {physical + 1U, false};
            }
            if (physical == leap) {
                return {leap, true};
            }
            return {physical, false};
        }
    };

    template<
            int FirstSupportedYear,
            int LastSupportedYear,
            gregorian_date DayGanzhiAnchorDate,
            unsigned DayGanzhiAnchorIndex,
            const std::array<
                    std::uint64_t,
                    supported_year_count<FirstSupportedYear, LastSupportedYear>()
            > &PackedYears,
            const std::array<
                    std::array<std::uint64_t, packed_solar_term_word_count>,
                    supported_year_count<FirstSupportedYear, LastSupportedYear>()
            > &PackedSolarTerms
    >
        /**
         * @brief Alias for the generated calendar adapter type.
         */
    using calendar = basic_calendar<
            FirstSupportedYear,
            LastSupportedYear,
            DayGanzhiAnchorDate,
            DayGanzhiAnchorIndex,
            PackedYears,
            PackedSolarTerms
    >;

    /**
     * @brief Converts a Heavenly Stem to text.
     */
    [[nodiscard]] inline std::string to_string(
            heavenly_stem value,
            text_style style = text_style::hans_cn
    ) {
        const auto i = static_cast<std::size_t>(value);
        switch (style) {
            case text_style::hans_cn:
            case text_style::hant_cn:
                return std::string{detail::stems_hans[i]};
            case text_style::pinyin:
                return std::string{detail::stems_pinyin[i]};
            case text_style::eon_mun_ko_cn:
                return std::string{detail::stems_eon_mun[i]};
            case text_style::numeric:
                return std::to_string(i);
        }
        return {};
    }

    /**
     * @brief Converts an Earthly Branch to text.
     */
    [[nodiscard]] inline std::string to_string(
            earthly_branch value,
            text_style style = text_style::hans_cn
    ) {
        const auto i = static_cast<std::size_t>(value);
        switch (style) {
            case text_style::hans_cn:
            case text_style::hant_cn:
                return std::string{detail::branches_hans[i]};
            case text_style::pinyin:
                return std::string{detail::branches_pinyin[i]};
            case text_style::eon_mun_ko_cn:
                return std::string{detail::branches_eon_mun[i]};
            case text_style::numeric:
                return std::to_string(i);
        }
        return {};
    }

    /**
     * @brief Converts a solar term to text.
     */
    [[nodiscard]] inline std::string to_string(
            solar_term value,
            text_style style = text_style::hans_cn
    ) {
        const auto i = static_cast<std::size_t>(value);
        if (i >= solar_term_count) {
            return {};
        }

        switch (style) {
            case text_style::hans_cn:
                return std::string{detail::solar_terms_hans[i]};
            case text_style::hant_cn:
                return std::string{detail::solar_terms_hant_cn[i]};
            case text_style::pinyin:
                return std::string{detail::solar_terms_pinyin[i]};
            case text_style::eon_mun_ko_cn:
                return std::string{detail::solar_terms_eon_mun[i]};
            case text_style::numeric:
                return std::to_string(i);
        }
        return {};
    }

    /**
     * @brief Converts a Ganzhi value to text.
     */
    [[nodiscard]] inline std::string to_string(
            ganzhi value,
            text_style style = text_style::hans_cn
    ) {
        if (style == text_style::numeric) {
            return std::to_string(static_cast<unsigned>(value.index));
        }

        std::string text = to_string(value.stem(), style);
        if (style == text_style::pinyin) {
            text.push_back('-');
        }
        text += to_string(value.branch(), style);
        return text;
    }

    /**
     * @brief Converts Four Pillars to four text fields.
     */
    [[nodiscard]] inline four_pillars_text to_string(
            four_pillars value,
            text_style style = text_style::hans_cn
    ) {
        return {
                to_string(value.year, style),
                to_string(value.month, style),
                to_string(value.day, style),
                to_string(value.hour, style)
        };
    }

    /**
     * @brief Joins Four Pillars text with a separator.
     */
    [[nodiscard]] inline std::string join(
            four_pillars value,
            text_style style = text_style::hans_cn,
            std::string_view separator = " "
    ) {
        const auto year = to_string(value.year, style);
        const auto month = to_string(value.month, style);
        const auto day = to_string(value.day, style);
        const auto hour = to_string(value.hour, style);

        std::string out;
        out.reserve(
                year.size()
                + month.size()
                + day.size()
                + hour.size()
                + separator.size() * 3
        );

        out += year;
        out += separator;
        out += month;
        out += separator;
        out += day;
        out += separator;
        out += hour;

        return out;
    }

}

namespace lunisolar {

    /**
     * @brief Structured-binding accessor for <code>chinese_date</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, chinese_date>
    && I < 4
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).year);
        } else if constexpr (I == 1) {
            return (std::forward<T>(value).month);
        } else if constexpr (I == 2) {
            return (std::forward<T>(value).day);
        } else {
            return (std::forward<T>(value).leap);
        }
    }

    /**
     * @brief Structured-binding accessor for <code>gregorian_date</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, gregorian_date>
    && I < 3
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).year);
        } else if constexpr (I == 1) {
            return (std::forward<T>(value).month);
        } else {
            return (std::forward<T>(value).day);
        }
    }

    /**
     * @brief Structured-binding accessor for <code>local_date_time_parts</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, local_date_time_parts>
    && I < 4
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).date);
        } else if constexpr (I == 1) {
            return (std::forward<T>(value).hour);
        } else if constexpr (I == 2) {
            return (std::forward<T>(value).minute);
        } else {
            return (std::forward<T>(value).second);
        }
    }

    /**
     * @brief Structured-binding accessor for <code>four_pillars</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, four_pillars>
    && I < 4
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).year);
        } else if constexpr (I == 1) {
            return (std::forward<T>(value).month);
        } else if constexpr (I == 2) {
            return (std::forward<T>(value).day);
        } else {
            return (std::forward<T>(value).hour);
        }
    }

    /**
     * @brief Structured-binding accessor for <code>four_pillars_text</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, four_pillars_text>
    && I < 4
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).year);
        } else if constexpr (I == 1) {
            return (std::forward<T>(value).month);
        } else if constexpr (I == 2) {
            return (std::forward<T>(value).day);
        } else {
            return (std::forward<T>(value).hour);
        }
    }

    /**
     * @brief Structured-binding accessor for <code>solar_term_year_month</code>.
     */
    template<std::size_t I, class T>
    requires (
    std::is_same_v<std::remove_cvref_t<T>, solar_term_year_month>
    && I < 2
    )
    [[nodiscard]] constexpr decltype(auto) get(T &&value) noexcept {
        if constexpr (I == 0) {
            return (std::forward<T>(value).year);
        } else {
            return (std::forward<T>(value).month);
        }
    }

}

namespace std {

    template<>
    struct tuple_size<lunisolar::chinese_date>
            : integral_constant<size_t, 4> {
    };

    template<size_t I> requires (I < 4)
    struct tuple_element<I, lunisolar::chinese_date> {
        using type = tuple_element_t<I, tuple<int, unsigned, unsigned, bool>>;
    };

    template<>
    struct tuple_size<lunisolar::gregorian_date>
            : integral_constant<size_t, 3> {
    };

    template<size_t I> requires (I < 3)
    struct tuple_element<I, lunisolar::gregorian_date> {
        using type = tuple_element_t<I, tuple<int, unsigned, unsigned>>;
    };

    template<>
    struct tuple_size<lunisolar::local_date_time_parts>
            : integral_constant<size_t, 4> {
    };

    template<size_t I> requires (I < 4)
    struct tuple_element<I, lunisolar::local_date_time_parts> {
        using type = tuple_element_t<
                I,
                tuple<lunisolar::gregorian_date, unsigned, unsigned, unsigned>
        >;
    };

    template<>
    struct tuple_size<lunisolar::four_pillars>
            : integral_constant<size_t, 4> {
    };

    template<size_t I> requires (I < 4)
    struct tuple_element<I, lunisolar::four_pillars> {
        using type = tuple_element_t<
                I,
                tuple<
                        lunisolar::ganzhi,
                        lunisolar::ganzhi,
                        lunisolar::ganzhi,
                        lunisolar::ganzhi
                >
        >;
    };

    template<>
    struct tuple_size<lunisolar::four_pillars_text>
            : integral_constant<size_t, 4> {
    };

    template<size_t I> requires (I < 4)
    struct tuple_element<I, lunisolar::four_pillars_text> {
        using type = tuple_element_t<
                I,
                tuple<std::string, std::string, std::string, std::string>
        >;
    };

    template<>
    struct tuple_size<lunisolar::solar_term_year_month>
            : integral_constant<size_t, 2> {
    };

    template<size_t I> requires (I < 2)
    struct tuple_element<I, lunisolar::solar_term_year_month> {
        using type = tuple_element_t<I, tuple<int, unsigned>>;
    };
}
